# Generated by Django 4.0.6 on 2022-07-28 18:19

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.CharField(max_length=500, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to=main_page.models.About.get_file_name2, verbose_name='Фото')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя партнёра')),
                ('logo', models.ImageField(upload_to=main_page.models.Clients.getfilename4, verbose_name='Логотип партнёра')),
                ('link', models.URLField(verbose_name='Ссылка на сайт партнёра')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя и Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Сообщениe клиента',
                'verbose_name_plural': 'Сообщения клиентов',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.CharField(max_length=100, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to=main_page.models.Portfolio.get_file_name, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('desc', models.CharField(max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('fas fa-shopping-cart fa-stack-1x fa-inverse', 'Shopping'), ('fas fa-laptop fa-stack-1x fa-inverse', 'Laptop'), ('fas fa-lock fa-stack-1x fa-inverse', 'Security')], max_length=200, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервис',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя и Фамилия')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to=main_page.models.Team.get_file_name3, verbose_name='Фото')),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
