# Generated by Django 4.0.6 on 2022-07-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='possition',
            field=models.CharField(choices=[('1', 'col-lg-4 col-sm-6 mb-4'), ('2', 'col-lg-4 col-sm-6 mb-4'), ('3', 'col-lg-4 col-sm-6 mb-4'), ('4', 'col-lg-4 col-sm-6 mb-4 mb-lg-0'), ('5', 'col-lg-4 col-sm-6 mb-4 mb-sm-0'), ('6', 'col-lg-4 col-sm-6')], default='', max_length=50, verbose_name='Позиция'),
        ),
    ]
