# Generated by Django 4.0.6 on 2022-07-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_portfolio_possition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('privacy_policy', models.URLField(verbose_name='Пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Нижняя строка',
                'verbose_name_plural': 'Нижняя строка',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='possition',
            field=models.CharField(choices=[('col-lg-4 col-sm-6 mb-4', '1'), ('col-lg-4 col-sm-6 mb-4', '2'), ('col-lg-4 col-sm-6 mb-4', '3'), ('col-lg-4 col-sm-6 mb-4 mb-lg-0', '4'), ('col-lg-4 col-sm-6 mb-4 mb-sm-0', '5'), ('col-lg-4 col-sm-6', '6')], default='', max_length=50, verbose_name='Позиция'),
        ),
    ]
