# Generated by Django 4.0.6 on 2022-08-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_footer_alter_portfolio_possition'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='big_desc',
            field=models.CharField(default='', max_length=500, verbose_name='Большое описание'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='privacy_policy',
            field=models.URLField(blank=True, verbose_name='Пользовательское соглашение'),
        ),
    ]
